name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          port: 22
          script_stop: true
          debug: true
          script: |
            cd app/server-api
            sudo rm -rf car-rental-express
            git clone https://github.com/AchmadArifaturrohman/car-rental-express.git 
            cd car-rental-express
            sudo docker compose up -d --build --rm
